metrics:
  db.io:
    description: The number of bytes sent or received to/from all clients.
    type: Counter
    unit: By
  db.connections:
    description: The number of connection attempts (successful or not) to the database.
    type: Counter
    unit: "{connection}"
  db.client.connection.count:
    description: The number of client connections to the database.
    type: UpDownCounter
    unit: "{connection}"
  db.uptime:
    description: The total number of seconds the server has been up.
    type: Gauge
    unit: s
  db.queries:
    description: The total number of statements executed by the server, including statements within stored programs but excluding `COM_PING` and `COM_STATISTICS` commands.
    type: Counter
    unit: "{statement}"
